import type { Product, FAQ, Category } from './types';

export const CONTACT = {
  address: 'Main Road, Madhira, Telangana 507203',
  phone: '+91 99492 78485',
  phoneRaw: '919949278485',
  instagram: 'https://www.instagram.com/sri_parameshwari_sweets/',
  instagramHandle: '@sri_parameshwari_sweets',
  rating: '4.5',
  timings: 'Open Daily 6:30 AM – 10:15 PM',
  mapsUrl: 'https://www.google.com/maps?q=16.9185278,80.3621667',
  mapsEmbed: 'https://www.google.com/maps?q=16.9185278,80.3621667&z=17&output=embed',
};

export const CATEGORIES: { key: Category; label: string }[] = [
  { key: 'all', label: 'All Items' },
  { key: 'ghee-specials', label: 'Pure Ghee Specials' },
  { key: 'andhra-sweets', label: 'Traditional Andhra Sweets' },
  { key: 'kaju-dryfruit', label: 'Kaju & Dry Fruit' },
  { key: 'savory-mixtures', label: 'Hot & Savory Mixtures' },
  { key: 'festival-giftboxes', label: 'Festival Gift Boxes' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'bandar-laddu',
    name: 'Bandar Laddu (Thokkudu)',
    teluguName: 'బందరు లడ్డు',
    category: 'ghee-specials',
    description: 'Our signature ghee-fried gram flour laddu, delicately crumbled and hand-rolled to melt-in-mouth perfection.',
    image: 'https://images.pexels.com/photos/14774070/pexels-photo-14774070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 160, '500g': 310, '1kg': 600 },
    tags: ['Best Seller', 'Pure Ghee'],
  },
  {
    id: 'bellam-sunnundalu',
    name: 'Bellam Sunnundalu',
    teluguName: 'బెల్లం సున్నుండలు',
    category: 'andhra-sweets',
    description: 'Traditional jaggery urad dal ladoos — rich, nutty, and wholesome with pure ghee and organic bellam.',
    image: 'https://images.pexels.com/photos/7133663/pexels-photo-7133663.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 140, '500g': 270, '1kg': 520 },
    tags: ['Festive Favorite', 'Jaggery'],
  },
  {
    id: 'ghee-mysore-pak',
    name: 'Ghee Mysore Pak',
    teluguName: 'నెయ్ మైసూర్ పాక్',
    category: 'ghee-specials',
    description: 'Melt-in-mouth ghee Mysore Pak with a golden crumbly texture, made in the authentic royal style.',
    image: 'https://images.pexels.com/photos/7182054/pexels-photo-7182054.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 170, '500g': 330, '1kg': 640 },
    tags: ['Best Seller', 'Pure Ghee'],
  },
  {
    id: 'motichoor-laddu',
    name: 'Motichoor Special Laddu',
    teluguName: 'మోతీచూర్ లడ్డు',
    category: 'ghee-specials',
    description: 'Tiny gram flour pearls soaked in saffron syrup, hand-rolled into soft, aromatic laddus.',
    image: 'https://images.pexels.com/photos/16062642/pexels-photo-16062642.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 160, '500g': 310, '1kg': 600 },
    tags: ['Festive Favorite', 'Pure Ghee'],
  },
  {
    id: 'kaju-katli',
    name: 'Royal Kaju Katli',
    teluguName: 'కాజు కట్లీ',
    category: 'kaju-dryfruit',
    description: 'Diamond-cut cashew fudge with silver leaf — the quintessential celebration sweet of premium quality.',
    image: 'https://images.pexels.com/photos/10514163/pexels-photo-10514163.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 320, '500g': 620, '1kg': 1200 },
    tags: ['Best Seller', 'Premium'],
  },
  {
    id: 'kaju-pista-roll',
    name: 'Kaju Pista Roll',
    teluguName: 'కాజు పిస్తా రోల్',
    category: 'kaju-dryfruit',
    description: 'Layered cashew and pistachio rolls with a vibrant green pista filling and delicate silver varak.',
    image: 'https://images.pexels.com/photos/18488310/pexels-photo-18488310.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 340, '500g': 660, '1kg': 1280 },
    tags: ['Premium', 'Festive Favorite'],
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun / Kala Jamun',
    teluguName: 'గులాబ్ జామ్',
    category: 'andhra-sweets',
    description: 'Soft, golden khoya dumplings soaked in fragrant rose-cardamom syrup. Served warm or at room temperature.',
    image: 'https://images.pexels.com/photos/9198596/pexels-photo-9198596.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 150, '500g': 290, '1kg': 560 },
    tags: ['Best Seller'],
  },
  {
    id: 'ghee-boondi',
    name: 'Ghee Boondi Mithai',
    teluguName: 'నెయ్ బూంది',
    category: 'ghee-specials',
    description: 'Soft, ghee-soaked gram flour boondi sweetened with saffron and cardamom — a temple-style classic.',
    image: 'https://images.pexels.com/photos/8887052/pexels-photo-8887052.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 150, '500g': 290, '1kg': 560 },
    tags: ['Pure Ghee'],
  },
  {
    id: 'malai-peda',
    name: 'Malai Peda / Kesar Peda',
    teluguName: 'మలాయ్ పేడా',
    category: 'andhra-sweets',
    description: 'Slow-cooked thickened milk pedas with saffron threads and cardamom — smooth, creamy and aromatic.',
    image: 'https://images.pexels.com/photos/11484120/pexels-photo-11484120.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 160, '500g': 310, '1kg': 600 },
    tags: ['Festive Favorite'],
  },
  {
    id: 'madhira-mixture',
    name: 'Spicy Madhira Mixture',
    teluguName: 'మధిర మిక్సర్',
    category: 'savory-mixtures',
    description: 'Our signature spicy crunchy mixture with sev, boondi, fried curry leaves and a secret spice blend.',
    image: 'https://images.pexels.com/photos/39524792/pexels-photo-39524792.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 90, '500g': 170, '1kg': 330 },
    tags: ['Best Seller', 'Savory'],
  },
  {
    id: 'chekkalu',
    name: 'Pappu Chekkalu',
    teluguName: 'పప్పు చెక్కలు',
    category: 'savory-mixtures',
    description: 'Crispy rice flour crackers studded with split yellow dal — a timeless Andhra tea-time snack.',
    image: 'https://images.pexels.com/photos/17480807/pexels-photo-17480807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 80, '500g': 150, '1kg': 290 },
    tags: ['Savory', 'Traditional'],
  },
  {
    id: 'murukku',
    name: 'Murukku / Janthikalu',
    teluguName: 'మురుకులు',
    category: 'savory-mixtures',
    description: 'Traditional butter chakli spirals — crisp, light and seasoned with cumin and sesame.',
    image: 'https://images.pexels.com/photos/9832636/pexels-photo-9832636.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 90, '500g': 170, '1kg': 330 },
    tags: ['Savory', 'Traditional'],
  },
  {
    id: 'ribbon-pakoda',
    name: 'Ribbon Pakoda / Kara Sev',
    teluguName: 'రిబ్బన్ పకోడా',
    category: 'savory-mixtures',
    description: 'Flat, crunchy ribbons of spiced gram flour with a fiery kick — the perfect savory companion.',
    image: 'https://images.pexels.com/photos/5992272/pexels-photo-5992272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 80, '500g': 150, '1kg': 290 },
    tags: ['Savory'],
  },
  {
    id: 'festival-giftbox',
    name: 'Premium Festival Assorted Gift Box',
    teluguName: 'పండుగ బహుమతి పెట్ట',
    category: 'festival-giftboxes',
    description: 'Luxury 1kg assorted gift box with 6 signature varieties — elegantly packed for Diwali, Sankranti & weddings.',
    image: 'https://images.pexels.com/photos/28769884/pexels-photo-28769884.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prices: { '250g': 400, '500g': 750, '1kg': 1450 },
    tags: ['Festive Favorite', 'Premium', 'Gift Box'],
  },
];

export const FAQS: FAQ[] = [
  { id: 1, category: 'Ingredients', question: 'Are all sweets prepared using pure ghee?', answer: 'Yes! Our signature sweets (Bandar Laddu, Mysore Pak, Sunnundalu, Halwa) are prepared using 100% pure cow ghee with traditional recipes and no compromises on purity.' },
  { id: 2, category: 'Ingredients', question: 'Do you offer sugar-free sweets for diabetics?', answer: 'Yes, we make special sugar-free and jaggery-based sweets like Bellam Sunnundalu and dry fruit bites upon prior order.' },
  { id: 3, category: 'Ingredients', question: 'What is the shelf life of your ghee sweets?', answer: 'Most pure ghee sweets last 12–15 days at room temperature. In an airtight container in a cool place, they remain fresh for up to 25 days.' },
  { id: 4, category: 'Ingredients', question: 'What is the shelf life of milk and Bengali sweets?', answer: 'Fresh milk-based items (Kalakand, Rasgulla, Malai Peda) should be consumed within 2–3 days and stored in refrigeration.' },
  { id: 5, category: 'Ingredients', question: 'Do your savories and mixtures use fresh cooking oil?', answer: 'Absolutely. We use fresh, premium groundnut and vegetable oils with strict single-use cooking practices to guarantee crispiness and health standards.' },
  { id: 6, category: 'Ingredients', question: 'Are your sweets 100% vegetarian?', answer: 'Yes, our entire facility and all products are 100% pure vegetarian (lacto-vegetarian). We never use gelatin or animal fats.' },
  { id: 7, category: 'Ordering', question: 'How can I place an order online?', answer: 'You can select your sweets and desired weights (250g, 500g, 1kg) on this website and click "Order via WhatsApp". It sends your itemized list straight to our WhatsApp for quick confirmation.' },
  { id: 8, category: 'Ordering', question: 'What digital payment methods do you accept?', answer: 'We accept PhonePe, Google Pay, Paytm, UPI QR scan, and direct bank transfers. We also accept cash for in-store pickups.' },
  { id: 9, category: 'Ordering', question: 'Can I customize the sweet mix in a single gift box?', answer: 'Yes! You can curate custom 500g and 1kg assorted gift boxes with 4 to 6 varieties of your choice.' },
  { id: 10, category: 'Ordering', question: 'Is advance payment required for orders?', answer: 'For regular local pickup, you can pay at the counter. For bulk orders, custom event packaging, or bus parcel shipments, 50%–100% advance UPI payment is required.' },
  { id: 11, category: 'Ordering', question: 'Can I cancel or modify an order once sent?', answer: 'You can modify or cancel your order via WhatsApp within 30 minutes of sending it, before packing begins.' },
  { id: 12, category: 'Ordering', question: 'Do you offer daily discounts or combo packs?', answer: 'We offer special combo prices for festival seasons (Sankranti, Dasara, Diwali) and discounted rates on orders over 10 kg.' },
  { id: 13, category: 'Delivery', question: 'Do you provide home delivery within Madhira town?', answer: 'Yes, we offer local doorstep delivery within Madhira municipal limits. Nominal delivery charges may apply based on distance.' },
  { id: 14, category: 'Delivery', question: 'Can you deliver to nearby villages around Madhira?', answer: 'Yes, we arrange deliveries to neighboring areas around Madhira via local auto-rickshaw or courier for pre-booked orders.' },
  { id: 15, category: 'Delivery', question: 'Do you ship parcels to Hyderabad, Khammam, or Vijayawada?', answer: 'Yes! We offer convenient same-day or next-day bus parcel delivery (TSRTC / APSRTC) to main bus stations in Khammam, Vijayawada, Hyderabad, and nearby towns.' },
  { id: 16, category: 'Delivery', question: 'How does bus parcel delivery work?', answer: 'We pack the sweets in damage-resistant boxes, hand them to the RTC bus counter, and send you the bus number, driver/conductor contact, and parcel receipt for easy pickup.' },
  { id: 17, category: 'Delivery', question: 'How long does bus parcel shipping take?', answer: 'Orders dispatched in the morning typically reach Khammam or Vijayawada within 2–4 hours, and Hyderabad within 5–7 hours on the same day.' },
  { id: 18, category: 'Delivery', question: 'What are the shipping charges for parcel delivery?', answer: 'Bus parcel charges range from ₹80 to ₹250 depending on box weight and destination city.' },
  { id: 19, category: 'Catering', question: 'Do you supply sweets for weddings and family functions?', answer: 'Yes, catering for weddings, engagements, Gruhapravesham, and birth ceremonies is our specialty since 1977. We handle orders from 10 kg up to 500+ kg.' },
  { id: 20, category: 'Catering', question: 'How much advance notice is required for wedding orders?', answer: 'We recommend placing bulk orders at least 3–7 days in advance so we can prepare fresh batches specifically for your event date.' },
  { id: 21, category: 'Catering', question: 'Do you offer customized printed packaging for wedding giveaways?', answer: 'Yes, we can arrange custom wedding gift boxes, bride/groom name tags, and premium tin packaging for bulk requirements.' },
  { id: 22, category: 'Catering', question: 'Can we request a tasting sample before confirming a large wedding order?', answer: 'Yes, you can visit our Madhira store anytime to taste sample batches of our signature sweets.' },
  { id: 23, category: 'Catering', question: 'Do you supply corporate Diwali or New Year gift boxes?', answer: 'Yes, we provide corporate sweet and dry-fruit gift hampers with custom branding options.' },
  { id: 24, category: 'Catering', question: 'Can we hire your sweet master chefs for live on-site sweet making?', answer: 'For major local events and weddings, on-site live hot jalebi/sweet counters can be arranged upon prior agreement.' },
  { id: 25, category: 'Timings', question: 'Where is Sri Parameswari Sweets located?', answer: 'We are in Madhira, Khammam District, Telangana 507203 (16°55\'06.7"N 80°21\'43.8"E). Use the “Get Directions” link on this site to open the exact pin on Google Maps.' },
  { id: 26, category: 'Timings', question: 'What are the daily store timings?', answer: 'We are open 7 days a week from 6:30 AM in the morning to 10:15 PM at night.' },
  { id: 27, category: 'Timings', question: 'Are you open during festival holidays?', answer: 'Yes, we are fully open with extended morning hours during Sankranti, Ugadi, Vinayaka Chavithi, Dasara, and Diwali.' },
  { id: 28, category: 'Timings', question: 'What are the peak busy hours at the shop?', answer: 'Mornings between 8:00 AM – 11:00 AM and evenings between 5:30 PM – 9:00 PM are usually the busiest.' },
  { id: 29, category: 'Timings', question: 'What hygiene precautions do you maintain?', answer: 'We maintain clean stainless-steel preparation units, food-grade gloves, daily sanitized counters, and tamper-evident packaging.' },
  { id: 30, category: 'Timings', question: 'Who do I contact directly for urgent questions?', answer: 'You can call or WhatsApp our master counter directly at +91 99492 78485.' },
];
